"""Static defaults for face/person snippet extraction and linking.

These values are intentionally code-level defaults so production does not need
an env var for every tuning knob. Secrets and model selection remain env-driven.
"""

# Extraction policy
SNIPPET_FACE_MODE = "precision"
SNIPPET_REQUIRE_MEDIAPIPE = True
SNIPPET_ENABLE_HAAR_FALLBACK = False
SNIPPET_ENABLE_HAAR_ASSIST = True
SNIPPET_ENABLE_LLM_FACE_VERIFY = True
SNIPPET_SKIP_WHEN_METADATA_NO_PEOPLE = False
SNIPPET_CREATE_PERSON_CONTEXT = False

# Detection thresholds
MEDIAPIPE_FACE_DETECTION_MIN_CONFIDENCE = 0.35
MEDIAPIPE_MODEL_SELECTION = 0
MEDIAPIPE_ENABLE_DUAL_MODEL = True
HAAR_FACE_DETECTION_MIN_CONFIDENCE = 0.55
SNIPPET_FACE_MIN_SHARPNESS = 90.0
SNIPPET_FACE_MIN_AREA_RATIO = 0.003
SNIPPET_FACE_MAX_AREA_RATIO = 0.45
SNIPPET_FACE_MIN_SIDE_PX = 28
SNIPPET_FACE_MIN_ASPECT_RATIO = 0.55
SNIPPET_FACE_MAX_ASPECT_RATIO = 1.65
SNIPPET_LLM_FACE_MIN_CONF = 0.90
SNIPPET_FACE_VERIFY_MIN_SIDE_PX = 224
MEDIAPIPE_FACE_MIN_SHARPNESS = 8.0
HAAR_FACE_MIN_SHARPNESS = 8.0

VIDEO_SAMPLE_SECONDS = 0.5
MIN_VIDEO_SAMPLE_STRIDE = 6
VIDEO_USE_METADATA_FACE_WINDOWS = True
VIDEO_FACE_WINDOW_PADDING_MS = 900
VIDEO_FACE_SAMPLES_PER_WINDOW = 3
VIDEO_BASELINE_SAMPLES = 4
SNIPPET_MAX_CANDIDATES_PER_FRAME = 2
SNIPPET_MAX_LLM_VERIFICATIONS_PER_ASSET = 24
SNIPPET_MAX_ACCEPTED_FACES_PER_ASSET = 8
SNIPPET_ALLOW_CONTEXT_RECOVERY = True
SNIPPET_CONTEXT_RECOVERY_MIN_DETECTOR_SCORE = 0.55
SNIPPET_CONTEXT_RECOVERY_MIN_CONTEXT_CONF = 0.55
SNIPPET_CONTEXT_RECOVERY_MAX_NOT_PERSON_CONF = 0.45

# Identity linking thresholds
SNIPPET_AUTO_ATTACH_MIN_SIM = 0.975
SNIPPET_AUTO_ATTACH_MIN_MARGIN = 0.05
SNIPPET_SUGGEST_MIN_SIM = 0.94
SNIPPET_STRICT_MIN_QUALITY_SCORE = 0.50
SNIPPET_REQUIRE_FACE_VERIFICATION = True
SNIPPET_STRICT_MIN_FACE_VERIFICATION_CONF = 0.90
