"""add_timeline_tables

Revision ID: 2b3d6522e78b
Revises: bef716534af4
Create Date: 2026-01-15 03:25:19.147366

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2b3d6522e78b"
down_revision = "bef716534af4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timelines",
        sa.Column("timeline_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "global_start_time", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "timeline_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.project_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("timeline_id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index(
        "ix_timelines_project_id", "timelines", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_timelines_timeline_id"), "timelines", ["timeline_id"], unique=True
    )
    op.create_table(
        "timeline_checkpoints",
        sa.Column("checkpoint_id", sa.UUID(), nullable=False),
        sa.Column("timeline_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.String(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["timeline_id"], ["timelines.timeline_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("checkpoint_id"),
    )
    op.create_index(
        op.f("ix_timeline_checkpoints_checkpoint_id"),
        "timeline_checkpoints",
        ["checkpoint_id"],
        unique=True,
    )
    op.create_index(
        "ix_timeline_checkpoints_created_at",
        "timeline_checkpoints",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_timeline_checkpoints_timeline_id",
        "timeline_checkpoints",
        ["timeline_id"],
        unique=False,
    )
    op.create_index(
        "ix_timeline_checkpoints_timeline_version",
        "timeline_checkpoints",
        ["timeline_id", "version"],
        unique=True,
    )
    op.create_table(
        "timeline_operations",
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("checkpoint_id", sa.UUID(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column(
            "operation_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"],
            ["timeline_checkpoints.checkpoint_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("operation_id"),
    )
    op.create_index(
        "ix_timeline_operations_checkpoint_id",
        "timeline_operations",
        ["checkpoint_id"],
        unique=False,
    )
    op.create_index(
        "ix_timeline_operations_created_at",
        "timeline_operations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timeline_operations_operation_id"),
        "timeline_operations",
        ["operation_id"],
        unique=True,
    )
    op.create_index(
        "ix_timeline_operations_operation_type",
        "timeline_operations",
        ["operation_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_timeline_operations_operation_type", table_name="timeline_operations"
    )
    op.drop_index(
        op.f("ix_timeline_operations_operation_id"), table_name="timeline_operations"
    )
    op.drop_index("ix_timeline_operations_created_at", table_name="timeline_operations")
    op.drop_index(
        "ix_timeline_operations_checkpoint_id", table_name="timeline_operations"
    )
    op.drop_table("timeline_operations")
    op.drop_index(
        "ix_timeline_checkpoints_timeline_version", table_name="timeline_checkpoints"
    )
    op.drop_index(
        "ix_timeline_checkpoints_timeline_id", table_name="timeline_checkpoints"
    )
    op.drop_index(
        "ix_timeline_checkpoints_created_at", table_name="timeline_checkpoints"
    )
    op.drop_index(
        op.f("ix_timeline_checkpoints_checkpoint_id"), table_name="timeline_checkpoints"
    )
    op.drop_table("timeline_checkpoints")
    op.drop_index(op.f("ix_timelines_timeline_id"), table_name="timelines")
    op.drop_index("ix_timelines_project_id", table_name="timelines")
    op.drop_table("timelines")
    # ### end Alembic commands ###
