"""initial schema with vector support

Revision ID: bef716534af4
Revises: 
Create Date: 2026-01-15 02:35:20.225955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'bef716534af4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.session_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_summary', sa.String(), nullable=False),
    sa.Column('asset_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notable_shots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_faces', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_technical', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_speakers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indexing_status', sa.String(), nullable=False),
    sa.Column('indexing_error', sa.String(), nullable=True),
    sa.Column('indexing_started_at', sa.DateTime(), nullable=True),
    sa.Column('indexing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('indexing_attempts', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('transcript_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', COALESCE(asset_transcript->>'text', ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    op.create_index('ix_assets_embedding', 'assets', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_assets_transcript_tsv', 'assets', ['transcript_tsv'], unique=False, postgresql_using='gin')
    op.create_table('video_outputs',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_video_outputs_video_id'), 'video_outputs', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_outputs_video_id'), table_name='video_outputs')
    op.drop_table('video_outputs')
    op.drop_index('ix_assets_transcript_tsv', table_name='assets', postgresql_using='gin')
    op.drop_index('ix_assets_embedding', table_name='assets', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

